apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app-2
  namespace: default
spec:
  interval: 1m0s
  ref:
    # branch: fluxcd-2022
    branch: fluxcd
  # url: https://github.com/marcel-dempers/docker-development-youtube-series
  url: https://github.com/hongphuc5497/docker-development-yt-series.git
  secretRef:
    name: flux-system
